### ISSUE TITLE
Use 'validate: type: bool' for each toggle to save value as false|true

### ISSUE THREAD

**Issue by pamtbaau** [wernerjoss/grav-plugin-fullcalendar#41]
Toggles in blueprints.yaml, are now being saved as strings containing `'0'` or `'1'`. These values might not be intuitive to non-dev users. Moreover, the docs use `false|true` values.

When using the following toggle definition, the value will be saved as `true` or `false`:
```
enabled:
    type: toggle
    label: Plugin status
    highlight: 1
    default: 1
    options:
        1: Enabled
        0: Disabled
    validate:
        type: bool
```
